PROGRAM split
IMPLICIT NONE

INTEGER:: I

DOUBLE PRECISION :: A(3)

OPEN(1 ,FILE="Bed.dat",FORM="FORMATTED")
OPEN(11, FILE="X.dat",FORM="FORMATTED")
OPEN(12, FILE="Y.dat",FORM="FORMATTED")
OPEN(13, FILE="Z.dat",FORM="FORMATTED")

DO 10 I = 1,2043
READ(1,*) A(1),A(2),A(3)
WRITE(11,*) A(1)
WRITE(12,*) A(2)
WRITE(13,*) A(3)
10 CONTINUE


END PROGRAM
